### ISSUE TITLE
Error in running run.py

### ISSUE THREAD

**Issue by junhyeokahn** [befelix/safe-exploration#13]
Hello,
Thanks for maintaining this repository!

While I am running a script ```python run.py --scenario_config journal_experiment_configs/cart_pole_rl_cautious_mpc_nperf=5.py```
I am getting the below error msg.
```
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    run_scenario(args)
  File "run.py", line 86, in run_scenario
    run_episodic(conf)
  File "/Users/junhyeokahn/Repository/safe-exploration/safe_exploration/episode_runner.py", line 65, in run_episodic
    obs_frequency=conf.obs_frequency)
  File "/Users/junhyeokahn/Repository/safe-exploration/safe_exploration/episode_runner.py", line 160, in do_rollout
    action, exit_code = solver.get_action(state)  # ,lqr_only = True)
  File "/Users/junhyeokahn/Repository/safe-exploration/safe_exploration/cautious_mpc.py", line 247, in get_action
    return self._get_solution(sol, crash, x0_mu, k_fb_0, verbose)
  File "/Users/junhyeokahn/Repository/safe-exploration/safe_exploration/cautious_mpc.py", line 284, in _get_solution
    u_apply, exit_code = self._get_old_solution(p_0)
  File "/Users/junhyeokahn/Repository/safe-exploration/safe_exploration/cautious_mpc.py", line 318, in _get_old_solution
    return u_apply.reshape(self.n_u, ), exit_code
  File "/Users/junhyeokahn/.venv/safe_exploration/lib/python3.7/site-packages/casadi/casadi.py", line 7459, in reshape
    return _casadi.reshape(self,arg)
NotImplementedError: Wrong number or type of arguments for overloaded function 'reshape'.
  Possible prototypes are:
    reshape(Sparsity,(int,int))
    reshape(Sparsity,Sparsity)
    reshape(DM,(int,int))
    reshape(DM,Sparsity)
    reshape(SX,(int,int))
    reshape(SX,Sparsity)
    reshape(MX,(int,int))
    reshape(MX,Sparsity)
    reshape(Sparsity,int,int)
    reshape(DM,int,int)
    reshape(SX,int,int)
    reshape(MX,int,int)
  You have: '(DM,int)'
```
Could you help me how to fix this?

**Comment by junhyeokahn** [comment]
I think, in this [if statement](https://github.com/befelix/safe-exploration/blob/e6c0bc57b7b51fe3e3c97d51721893fe297b2b11/safe_exploration/cautious_mpc.py#L311), it should be like below

```
        if self.n_fail < self.T:
            u_apply = self.k_ff_old[self.n_fail, :]
            u_apply = np.array([u_apply])
            exit_code = 1
```
